### ISSUE TITLE
Bug & Suggestion

### ISSUE THREAD

**Issue by Yoon0117** [jaylinski/flockscreen#4]
Hey, I know you aren't really updating this but I think it's a great tool, maybe you should try advertising it a bit to get some users. It's really a hidden gem! Maybe a renaming or changing the icon, cuz flockscreen isn't the most relevant name tbh xD

Anyways, there's a bug where if I start flockscreen and lock it, then move my cursor to bring up the lock screen, it takes a photo. But for some reason
1. The photo is VERY dark and nothing is really visible, cranking the brightness up just barely reveals the outlines of things in the photo
2. After unlocking the mac, and I enable lock again, when I move my cursor no photo is taken. I have to quit and reopen flockscreen to enable a lock which will take a photo.

Just a suggestion, you should make it so the photos go into /Pictures/flockscreen instead of /Pictures

Thanks!

**Comment by jaylinski** [comment]
Thanks for the kind words!

Capturing the photo is tricky because the camera needs about a seconds to adjust its brightness:
https://github.com/jaylinski/flockscreen/blob/06e7f388e0c1345953daaa3f047b8fbadd463a80/flockscreen/util.swift#L34-L37
I'll update it to 500ms and do some tests on my Macbook.

I'll also take a look at the other bug you mentioned.

**Comment by Yoon0117** [comment]
Thank you for the reply, I'll make sure to check it out soon as you make the changes 👍

**Comment by jaylinski** [comment]
I fixed a bunch of issues (including the ones you reported) and added some improvements:

* https://github.com/jaylinski/flockscreen/commit/efcda888c636b93091079d43f8937b882c2dad97
* https://github.com/jaylinski/flockscreen/releases/tag/v0.2.0

If you encounter any other bugs, let me know.

Regarding "you should make it so the photos go into /Pictures/flockscreen instead of /Pictures": it's on my roadmap to make the folder configurable.

**Comment by Yoon0117** [comment]
appreciate it, tysm!
